#Himanshu(member-4), waste database and its logic

waste_database = {
    #wet waste(green bin)
    "apple": {"category": "wet waste"},
    "apple peel": {"category": "wet waste"},
    "eggs": {"category": "wet waste"},
    "banana peel": {"category": "wet waste"},
    "banana": {"category": "wet waste"},
    "orange peel": {"category": "wet waste"},
    "orange": {"category": "wet waste"},
    "pear": {"category": "wet waste"},
    "plum": {"category": "wet waste"},
    "pineapple": {"category": "wet waste"},
    "watermelon": {"category": "wet waste"},
    "grape": {"category": "wet waste"},
    "grapefruit": {"category": "wet waste"},
    "kiwi": {"category": "wet waste"},
    "lemon": {"category": "wet waste"},
    "lime": {"category": "wet waste"},
    "mango": {"category": "wet waste"},
    "papaya": {"category": "wet waste"},
    "peach": {"category": "wet waste"},
    "strawberry": {"category": "wet waste"},
    "tomato": {"category": "wet waste"},
    "avocado": {"category": "wet waste"},
    "broccoli": {"category": "wet waste"},
    "carrot": {"category": "wet waste"},
    "cucumber": {"category": "wet waste"},
    "lettuce": {"category": "wet waste"},
    "spinach": {"category": "wet waste"},
    "potato": {"category": "wet waste"},
    "onion": {"category": "wet waste"},
    "garlic": {"category": "wet waste"},
    "ginger": {"category": "wet waste"},
    "cabbage": {"category": "wet waste"},
    "celery": {"category": "wet waste"},
    "corn": {"category": "wet waste"},
    "eggplant": {"category": "wet waste"},
    "peas": {"category": "wet waste"},
    "radish": {"category": "wet waste"},
    "beans": {"category": "wet waste"},
    "mushroom": {"category": "wet waste"},
    "butter": {"category": "wet waste"},
    "cheese": {"category": "wet waste"},
    "yogurt": {"category": "wet waste"},
    "milk": {"category": "wet waste"},
    "cream": {"category": "wet waste"},
    "sour cream": {"category": "wet waste"},
    "ice cream": {"category": "wet waste"},
    "egg": {"category": "wet waste"},
    "meat": {"category": "wet waste"},
    "fish": {"category": "wet waste"},
    "seafood": {"category": "wet waste"},
    "chicken": {"category": "wet waste"},
    "beef": {"category": "wet waste"},
    "pork": {"category": "wet waste"},
    "lamb": {"category": "wet waste"},
    "chicken bones": {"category": "wet waste"},
    "beef bones": {"category": "wet waste"},
    "pork bones": {"category": "wet waste"},
    "lamb bones": {"category": "wet waste"},
    "fish bones": {"category": "wet waste"},
    "seafood bones": {"category": "wet waste"},
    "blueberry": {"category": "wet waste"},
    "raspberry": {"category": "wet waste"},
    "blackberry": {"category": "wet waste"},
    "cherry pits": {"category": "wet waste"},
    "apricot": {"category": "wet waste"},
    "peach stone": {"category": "wet waste"},
    "pomegranate peel": {"category": "wet waste"},
    "pomegranate seeds": {"category": "wet waste"},
    "custard apple skin": {"category": "wet waste"},
    "guava": {"category": "wet waste"},
    "lychee skin": {"category": "wet waste"},
    "dragon fruit peel": {"category": "wet waste"},
    "coconut husk": {"category": "wet waste"},
    "coconut shell": {"category": "wet waste"},
    "jackfruit skin": {"category": "wet waste"},
    "broccoli stalk": {"category": "wet waste"},
    "corn cob": {"category": "wet waste"},
    "corn husk": {"category": "wet waste"},
    "cucumber skin": {"category": "wet waste"},
    "eggplant stem": {"category": "wet waste"},
    "garlic peel": {"category": "wet waste"},
    "ginger skin": {"category": "wet waste"},
    "mushroom stalks": {"category": "wet waste"},
    "bell pepper core": {"category": "wet waste"},
    "radish tops": {"category": "wet waste"},
    "coriander stems": {"category": "wet waste"},
    "mint stalks": {"category": "wet waste"},
    "curry leaves": {"category": "wet waste"},
    "spring onion roots": {"category": "wet waste"},
    "sweet potato peel": {"category": "wet waste"},
    "pumpkin skin": {"category": "wet waste"},
    "pumpkin seeds": {"category": "wet waste"},
    "okra head": {"category": "wet waste"},
    "pasta leftovers": {"category": "wet waste"},
    "noodle scraps": {"category": "wet waste"},
    "pizza crust": {"category": "wet waste"},
    "spoiled curry": {"category": "wet waste"},
    "stale cake": {"category": "wet waste"},
    "biscuit crumbs": {"category": "wet waste"},
    "bread crust": {"category": "wet waste"},
    "cheese rind": {"category": "wet waste"},
    "yogurt waste": {"category": "wet waste"},
    "butter scraps": {"category": "wet waste"},
    "tofu waste": {"category": "wet waste"},
    "soy milk residue": {"category": "wet waste"},
    "meat fat": {"category": "wet waste"},
    "shrimp shells": {"category": "wet waste"},
    "crab shells": {"category": "wet waste"},
    "mussel shells": {"category": "wet waste"},
    "pet food scraps": {"category": "wet waste"},
    "bird seed husks": {"category": "wet waste"},
    "wet cardboard": {"category": "wet waste"},
    "soiled paper towel": {"category": "wet waste"},
    "paper tea bags": {"category": "wet waste"},
    "loose leaf tea": {"category": "wet waste"},
    "wooden skewers": {"category": "wet waste"},
    "wooden toothpicks": {"category": "wet waste"},
    "natural cork": {"category": "wet waste"},
    "hay": {"category": "wet waste"},
    "sawdust": {"category": "wet waste"},
    "coffee grounds": {"category": "wet waste"},
    "used tea leaves": {"category": "wet waste"},
    "tea dust": {"category": "wet waste"},
    "sugarcane bagasse": {"category": "wet waste"},
    "sugarcane peel": {"category": "wet waste"},
    "citrus rind": {"category": "wet waste"},
    "beetroot peel": {"category": "wet waste"},
    "bottle gourd peel": {"category": "wet waste"},
    "ridge gourd peel": {"category": "wet waste"},
    "ash gourd peel": {"category": "wet waste"},
    "raw banana peel": {"category": "wet waste"},
    "cauliflower leaves": {"category": "wet waste"},
    "cauliflower stalk": {"category": "wet waste"},
    "capsicum stem": {"category": "wet waste"},
    "drumstick peels": {"category": "wet waste"},
    "fenugreek stems": {"category": "wet waste"},
    "dill stems": {"category": "wet waste"},
    "banana stem": {"category": "wet waste"},
    "banana flower": {"category": "wet waste"},
    "tamarind pulp": {"category": "wet waste"},
    "coconut pulp": {"category": "wet waste"},
    "leftover rice": {"category": "wet waste"},
    "leftover dal": {"category": "wet waste"},
    "leftover sabzi": {"category": "wet waste"},
    "curd rice leftovers": {"category": "wet waste"},
    "idli leftovers": {"category": "wet waste"},
    "dosa scraps": {"category": "wet waste"},
    "chapati scraps": {"category": "wet waste"},
    "khichdi leftovers": {"category": "wet waste"},
    "upma leftovers": {"category": "wet waste"},
    "poha leftovers": {"category": "wet waste"},
    "expired paneer": {"category": "wet waste"},
    "spoiled curd": {"category": "wet waste"},
    "moldy bread": {"category": "wet waste"},
    "spoiled cooked food": {"category": "wet waste"},
    "gravy leftovers": {"category": "wet waste"},
    "salad leftovers": {"category": "wet waste"},
    "fruit salad leftovers": {"category": "wet waste"},
    "juice pulp": {"category": "wet waste"},
    "watermelon rind": {"category": "wet waste"},
    "melon seeds": {"category": "wet waste"},
    "sunflower seed shells": {"category": "wet waste"},
    "peanut shells": {"category": "wet waste"},
    "pistachio shells": {"category": "wet waste"},
    "eggshells": {"category": "wet waste"},
    "flower waste": {"category": "wet waste"},
    "wilted flowers": {"category": "wet waste"},
    "leaf litter": {"category": "wet waste"},
    "grass clippings": {"category": "wet waste"},
    "small twigs": {"category": "wet waste"},
    "plant trimmings": {"category": "wet waste"},
    "compostable food wrappers": {"category": "wet waste"},
    "beet greens": {"category": "wet waste"},
    "turnip peel": {"category": "wet waste"},
    "zucchini peel": {"category": "wet waste"},
    "zucchini ends": {"category": "wet waste"},
    "bitter gourd seeds": {"category": "wet waste"},
    "bitter gourd pith": {"category": "wet waste"},
    "snake gourd peel": {"category": "wet waste"},
    "lauki peel": {"category": "wet waste"},
    "turai peel": {"category": "wet waste"},
    "yam peel": {"category": "wet waste"},
    "arbi peel": {"category": "wet waste"},
    "cassava peel": {"category": "wet waste"},
    "onion skins": {"category": "wet waste"},
    "shallot peel": {"category": "wet waste"},
    "leek tops": {"category": "wet waste"},
    "fennel stalks": {"category": "wet waste"},
    "parsley stems": {"category": "wet waste"},
    "basil stems": {"category": "wet waste"},
    "rosemary stems": {"category": "wet waste"},
    "thyme stems": {"category": "wet waste"},
    "mint leaves waste": {"category": "wet waste"},
    "coriander roots": {"category": "wet waste"},
    "tea bag strings": {"category": "wet waste"},
    "coffee filter paper": {"category": "wet waste"},
    "cocoa husk": {"category": "wet waste"},
    "cereal leftovers": {"category": "wet waste"},
    "oats leftovers": {"category": "wet waste"},
    "porridge leftovers": {"category": "wet waste"},
    "boiled rice starch": {"category": "wet waste"},
    "lentil rinse residue": {"category": "wet waste"},
    "chickpea skins": {"category": "wet waste"},
    "pea pods": {"category": "wet waste"},
    "bean pods": {"category": "wet waste"},
    "corn silk": {"category": "wet waste"},
    "pomegranate rind": {"category": "wet waste"},
    "mango seed": {"category": "wet waste"},
    "lychee seed": {"category": "wet waste"},
    "longan peel": {"category": "wet waste"},
    "sapota peel": {"category": "wet waste"},
    "custard apple seeds": {"category": "wet waste"},
    "guava seeds": {"category": "wet waste"},
    "orange pith": {"category": "wet waste"},
    "lemon pulp": {"category": "wet waste"},
    "cane juice residue": {"category": "wet waste"},
    "paneer whey residue": {"category": "wet waste"},
    "spoiled mayonnaise": {"category": "wet waste"},
    "spoiled sauce": {"category": "wet waste"},
    "pickle brine solids": {"category": "wet waste"},
    "fried batter scraps": {"category": "wet waste"},
    "used edible flowers": {"category": "wet waste"},
    "wilted spinach": {"category": "wet waste"},
    "wilted lettuce": {"category": "wet waste"},
    "houseplant dry leaves": {"category": "wet waste"},
    "coconut water pulp": {"category": "wet waste"},
    "compostable napkins": {"category": "wet waste"},
    "food-stained tissue": {"category": "wet waste"},
    "spoiled sprouts": {"category": "wet waste"},
    "sprout roots": {"category": "wet waste"},
    "fermented batter waste": {"category": "wet waste"},
    "idiyappam leftovers": {"category": "wet waste"},
    "mess food leftovers": {"category": "wet waste"},
    "hostel room dust": {"category": "wet waste"}, 

    #dry waste(blue bin)
    "plastic bottle": {"category": "dry waste"},
    "aluminum can": {"category": "dry waste"},
    "paper cup": {"category": "dry waste"},
    "cardboard box": {"category": "dry waste"},
    "glass jar": {"category": "dry waste"},
    "aluminum foil": {"category": "dry waste"},
    "plastic bag": {"category": "dry waste"},
    "styrofoam": {"category": "dry waste"},
    "plastic utensils": {"category": "dry waste"},
    "plastic straws": {"category": "dry waste"},
    "plastic packaging": {"category": "dry waste"},
    "paper packaging": {"category": "dry waste"},
    "plastic wrap": {"category": "dry waste"},
    "plastic food containers": {"category": "dry waste"},
    "plastic lids": {"category": "dry waste"},
    "plastic caps": {"category": "dry waste"},
    "plastic cutlery": {"category": "dry waste"},
    "plastic plates": {"category": "dry waste"},
    "plastic cups": {"category": "dry waste"},
    "plastic trays": {"category": "dry waste"},
    "plastic": {"category": "dry waste"},
    "paper": {"category": "dry waste"},
    "cardboard": {"category": "dry waste"},
    "aluminum": {"category": "dry waste"},
    "glass": {"category": "dry waste"},
    "metal": {"category": "dry waste"},
    "newspaper": {"category": "dry waste"},
    "old magazine": {"category": "dry waste"},
    "office paper": {"category": "dry waste"},
    "notebook paper": {"category": "dry waste"},
    "printer paper": {"category": "dry waste"},
    "junk mail": {"category": "dry waste"},
    "paper envelope": {"category": "dry waste"},
    "bubble mailer": {"category": "dry waste"},
    "paper brochure": {"category": "dry waste"},
    "paper flyer": {"category": "dry waste"},
    "paper bag clean": {"category": "dry waste"},
    "corrugated cardboard": {"category": "dry waste"},
    "cereal box": {"category": "dry waste"},
    "shoe box": {"category": "dry waste"},
    "toothpaste carton": {"category": "dry waste"},
    "egg carton paper": {"category": "dry waste"},
    "tissue box": {"category": "dry waste"},
    "paper tube": {"category": "dry waste"},
    "paperboard sleeve": {"category": "dry waste"},
    "paper label": {"category": "dry waste"},
    "greeting card": {"category": "dry waste"},
    "gift wrap paper": {"category": "dry waste"},
    "paper calendar": {"category": "dry waste"},
    "sticky notes": {"category": "dry waste"},
    "index cards": {"category": "dry waste"},
    "paper file folder": {"category": "dry waste"},
    "paper receipt": {"category": "dry waste"},
    "paper ticket": {"category": "dry waste"},
    "cardboard divider": {"category": "dry waste"},
    "pizza box clean": {"category": "dry waste"},
    "milk carton rinsed": {"category": "dry waste"},
    "juice carton rinsed": {"category": "dry waste"},
    "tetra pak carton": {"category": "dry waste"},
    "tetrapack": {"category": "dry waste"},
    "paper cup sleeve": {"category": "dry waste"},
    "kraft paper": {"category": "dry waste"},
    "pet bottle": {"category": "dry waste"},
    "hdpe bottle": {"category": "dry waste"},
    "detergent bottle": {"category": "dry waste"},
    "shampoo bottle": {"category": "dry waste"},
    "lotion bottle": {"category": "dry waste"},
    "medicine bottle plastic": {"category": "dry waste"},
    "yogurt cup plastic": {"category": "dry waste"},
    "takeaway container plastic": {"category": "dry waste"},
    "blister pack plastic": {"category": "dry waste"},
    "plastic clamshell": {"category": "dry waste"},
    "plastic jar": {"category": "dry waste"},
    "plastic drum small": {"category": "dry waste"},
    "plastic bucket broken": {"category": "dry waste"},
    "plastic hanger": {"category": "dry waste"},
    "plastic toy": {"category": "dry waste"},
    "plastic pen body": {"category": "dry waste"},
    "plastic marker body": {"category": "dry waste"},
    "plastic toothbrush": {"category": "dry waste"},
    "plastic comb": {"category": "dry waste"},
    "plastic bucket lid": {"category": "dry waste"},
    "plastic crate piece": {"category": "dry waste"},
    "plastic pipe piece": {"category": "dry waste"},
    "pvc pipe segment": {"category": "dry waste"},
    "plastic rope": {"category": "dry waste"},
    "nylon rope": {"category": "dry waste"},
    "bubble wrap clean": {"category": "dry waste"},
    "air pillow packaging": {"category": "dry waste"},
    "plastic mailer": {"category": "dry waste"},
    "ziplock bag clean": {"category": "dry waste"},
    "polypropylene bag": {"category": "dry waste"},
    "laminate pouch": {"category": "dry waste"},
    "snack wrapper clean": {"category": "dry waste"},
    "biscuit wrapper clean": {"category": "dry waste"},
    "chips packet clean": {"category": "dry waste"},
    "candy wrapper clean": {"category": "dry waste"},
    "bottle cap ring": {"category": "dry waste"},
    "plastic spool": {"category": "dry waste"},
    "cd case plastic": {"category": "dry waste"},
    "dvd case plastic": {"category": "dry waste"},
    "plastic cd spindle": {"category": "dry waste"},
    "plastic name badge": {"category": "dry waste"},
    "plastic keycard": {"category": "dry waste"},
    "acrylic sheet piece": {"category": "dry waste"},
    "thermocol sheet clean": {"category": "dry waste"},
    "plastic flower pot": {"category": "dry waste"},
    "nursery pot plastic": {"category": "dry waste"},
    "disposable razor plastic": {"category": "dry waste"},
    "plastic tape core": {"category": "dry waste"},
    "plastic measuring cup": {"category": "dry waste"},
    "plastic funnel": {"category": "dry waste"},
    "steel can": {"category": "dry waste"},
    "tin can": {"category": "dry waste"},
    "beverage can": {"category": "dry waste"},
    "metal lid": {"category": "dry waste"},
    "metal cap": {"category": "dry waste"},
    "food can": {"category": "dry waste"},
    "aerosol can empty": {"category": "dry waste"},
    "aluminum tray": {"category": "dry waste"},
    "steel spoon": {"category": "dry waste"},
    "steel fork": {"category": "dry waste"},
    "steel wire": {"category": "dry waste"},
    "copper wire": {"category": "dry waste"},
    "brass piece": {"category": "dry waste"},
    "iron nail": {"category": "dry waste"},
    "screw metal": {"category": "dry waste"},
    "bolt metal": {"category": "dry waste"},
    "metal hanger": {"category": "dry waste"},
    "metal clip": {"category": "dry waste"},
    "paper clip metal": {"category": "dry waste"},
    "stapler pin": {"category": "dry waste"},
    "metal chain": {"category": "dry waste"},
    "metal key": {"category": "dry waste"},
    "old lock": {"category": "dry waste"},
    "utensil handle metal": {"category": "dry waste"},
    "broken steel plate": {"category": "dry waste"},
    "glass bottle clear": {"category": "dry waste"},
    "glass bottle brown": {"category": "dry waste"},
    "glass bottle green": {"category": "dry waste"},
    "broken glass pieces": {"category": "dry waste"},
    "glass tumbler broken": {"category": "dry waste"},
    "glass bowl broken": {"category": "dry waste"},
    "glass plate broken": {"category": "dry waste"},
    "glass perfume bottle": {"category": "dry waste"},
    "glass medicine vial": {"category": "dry waste"},
    "glass candle jar": {"category": "dry waste"},
    "window glass piece": {"category": "dry waste"},
    "mirror piece": {"category": "dry waste"},
    "ceramic cup broken": {"category": "dry waste"},
    "ceramic plate broken": {"category": "dry waste"},
    "porcelain bowl broken": {"category": "dry waste"},
    "clay pot broken": {"category": "dry waste"},
    "terracotta shard": {"category": "dry waste"},
    "glass test tube": {"category": "dry waste"},
    "glass dropper bottle": {"category": "dry waste"},
    "glass food container": {"category": "dry waste"},
    "old cotton cloth": {"category": "dry waste"},
    "old jeans": {"category": "dry waste"},
    "old t shirt": {"category": "dry waste"},
    "worn socks": {"category": "dry waste"},
    "torn bedsheet": {"category": "dry waste"},
    "old towel": {"category": "dry waste"},
    "fabric scraps": {"category": "dry waste"},
    "jute bag old": {"category": "dry waste"},
    "leather belt old": {"category": "dry waste"},
    "leather wallet old": {"category": "dry waste"},
    "rubber band bunch": {"category": "dry waste"},
    "rubber glove torn": {"category": "dry waste"},
    "rubber slipper broken": {"category": "dry waste"},
    "rubber mat piece": {"category": "dry waste"},
    "bicycle tube rubber": {"category": "dry waste"},
    "eraser waste": {"category": "dry waste"},
    "wooden pencil shavings dry": {"category": "dry waste"},
    "wooden ruler broken": {"category": "dry waste"},
    "wood sawdust dry": {"category": "dry waste"},
    "cork sheet piece": {"category": "dry waste"},
    "exam papers": {"category": "dry waste"}, 
    "old assignments": {"category": "dry waste"}, 
    "broken scale": {"category": "dry waste"}, 
    "empty pen refill": {"category": "dry waste"}, 
    "plastic folder": {"category": "dry waste"}, 
    "lanyard ribbon": {"category": "dry waste"}, 
    "bottle": {"category": "dry waste"},
    "water bottle": {"category": "dry waste"},

    #hazardous waste(black bin)
    "battery": {"category": "hazardous waste"},
    "paint can": {"category": "hazardous waste"},
    "pesticide container": {"category": "hazardous waste"},
    "chemical bottle": {"category": "hazardous waste"},
    "light bulb": {"category": "hazardous waste"},
    "aerosol can full": {"category": "hazardous waste"},
    "expired medication": {"category": "hazardous waste"},
    "fluorescent tube": {"category": "hazardous waste"},
    "mercury thermometer": {"category": "hazardous waste"},
    "lead acid battery": {"category": "hazardous waste"},
    "nickel cadmium battery": {"category": "hazardous waste"},
    "lithium ion battery": {"category": "hazardous waste"},
    "button cell battery": {"category": "hazardous waste"},
    "car battery": {"category": "hazardous waste"},
    "household battery": {"category": "hazardous waste"},
    "paint brush with paint": {"category": "hazardous waste"},
    "paint roller with paint": {"category": "hazardous waste"},
    "paint tray with paint": {"category": "hazardous waste"},
    "pesticide sprayer": {"category": "hazardous waste"},
    "pesticide bottle": {"category": "hazardous waste"},
    "chemical spill": {"category": "hazardous waste"},
    "chemical container": {"category": "hazardous waste"},
    "chemical waste": {"category": "hazardous waste"},
    "alkaline aa battery": {"category": "hazardous waste"},
    "alkaline aaa battery": {"category": "hazardous waste"},
    "alkaline c battery": {"category": "hazardous waste"},
    "alkaline d battery": {"category": "hazardous waste"},
    "alkaline 9v battery": {"category": "hazardous waste"},
    "silver oxide battery": {"category": "hazardous waste"},
    "zinc carbon battery": {"category": "hazardous waste"},
    "rechargeable nimh battery": {"category": "hazardous waste"},
    "damaged lithium battery": {"category": "hazardous waste"},
    "swollen lithium battery": {"category": "hazardous waste"},
    "leaking battery": {"category": "hazardous waste"},
    "battery acid residue": {"category": "hazardous waste"},
    "battery terminals scrap": {"category": "hazardous waste"},
    "mercury button cell": {"category": "hazardous waste"},
    "fluorescent lamp": {"category": "hazardous waste"},
    "cfl bulb": {"category": "hazardous waste"},
    "halogen bulb": {"category": "hazardous waste"},
    "mercury vapor lamp": {"category": "hazardous waste"},
    "sodium vapor lamp": {"category": "hazardous waste"},
    "uv lamp": {"category": "hazardous waste"},
    "broken cfl bulb": {"category": "hazardous waste"},
    "broken fluorescent tube": {"category": "hazardous waste"},
    "broken mercury lamp": {"category": "hazardous waste"},
    "lamp ballast": {"category": "hazardous waste"},
    "hid bulb": {"category": "hazardous waste"},
    "xenon bulb": {"category": "hazardous waste"},
    "oil based paint residue": {"category": "hazardous waste"},
    "latex paint residue": {"category": "hazardous waste"},
    "paint thinner": {"category": "hazardous waste"},
    "turpentine waste": {"category": "hazardous waste"},
    "varnish can": {"category": "hazardous waste"},
    "wood stain can": {"category": "hazardous waste"},
    "lacquer thinner": {"category": "hazardous waste"},
    "epoxy resin waste": {"category": "hazardous waste"},
    "hardener container": {"category": "hazardous waste"},
    "adhesive solvent": {"category": "hazardous waste"},
    "contact cement can": {"category": "hazardous waste"},
    "spray paint can": {"category": "hazardous waste"},
    "ink thinner": {"category": "hazardous waste"},
    "printing ink waste": {"category": "hazardous waste"},
    "solvent soaked rag": {"category": "hazardous waste"},
    "degreaser bottle": {"category": "hazardous waste"},
    "rust remover": {"category": "hazardous waste"},
    "metal polish chemical": {"category": "hazardous waste"},
    "brake cleaner can": {"category": "hazardous waste"},
    "carburetor cleaner can": {"category": "hazardous waste"},
    "paint stripper": {"category": "hazardous waste"},
    "caustic soda container": {"category": "hazardous waste"},
    "acid cleaner bottle": {"category": "hazardous waste"},
    "drain cleaner chemical": {"category": "hazardous waste"},
    "toilet cleaner acid": {"category": "hazardous waste"},
    "bleach concentrate bottle": {"category": "hazardous waste"},
    "ammonia cleaner bottle": {"category": "hazardous waste"},
    "oven cleaner can": {"category": "hazardous waste"},
    "mold remover chemical": {"category": "hazardous waste"},
    "disinfectant concentrate": {"category": "hazardous waste"},
    "formaldehyde solution": {"category": "hazardous waste"},
    "xylene container": {"category": "hazardous waste"},
    "toluene container": {"category": "hazardous waste"},
    "acetone bottle": {"category": "hazardous waste"},
    "isopropyl alcohol waste": {"category": "hazardous waste"},
    "methanol container": {"category": "hazardous waste"},
    "chloroform container": {"category": "hazardous waste"},
    "hydrochloric acid bottle": {"category": "hazardous waste"},
    "sulfuric acid bottle": {"category": "hazardous waste"},
    "nitric acid bottle": {"category": "hazardous waste"},
    "phosphoric acid bottle": {"category": "hazardous waste"},
    "laboratory acid waste": {"category": "hazardous waste"},
    "laboratory base waste": {"category": "hazardous waste"},
    "oxidizer chemical bottle": {"category": "hazardous waste"},
    "peroxide chemical bottle": {"category": "hazardous waste"},
    "pool chlorine container": {"category": "hazardous waste"},
    "pool algaecide bottle": {"category": "hazardous waste"},
    "photographic developer": {"category": "hazardous waste"},
    "photographic fixer": {"category": "hazardous waste"},
    "etching chemical bottle": {"category": "hazardous waste"},
    "resin catalyst": {"category": "hazardous waste"},
    "fiberglass resin waste": {"category": "hazardous waste"},
    "epoxy hardener tube": {"category": "hazardous waste"},
    "silicone sealant tube": {"category": "hazardous waste"},
    "polyurethane foam can": {"category": "hazardous waste"},
    "wood preservative can": {"category": "hazardous waste"},
    "shoe polish chemical": {"category": "hazardous waste"},
    "furniture polish chemical": {"category": "hazardous waste"},
    "stain remover solvent": {"category": "hazardous waste"},
    "industrial cleaning solvent": {"category": "hazardous waste"},
    "used engine oil": {"category": "hazardous waste"},
    "used gear oil": {"category": "hazardous waste"},
    "used hydraulic oil": {"category": "hazardous waste"},
    "oil filter": {"category": "hazardous waste"},
    "fuel filter waste": {"category": "hazardous waste"},
    "coolant waste": {"category": "hazardous waste"},
    "brake fluid waste": {"category": "hazardous waste"},
    "transmission fluid waste": {"category": "hazardous waste"},
    "grease cartridge": {"category": "hazardous waste"},
    "antifreeze container": {"category": "hazardous waste"},
    "diesel additive bottle": {"category": "hazardous waste"},
    "petrol additive bottle": {"category": "hazardous waste"},
    "insecticide can": {"category": "hazardous waste"},
    "herbicide can": {"category": "hazardous waste"},
    "fungicide bottle": {"category": "hazardous waste"},
    "rodenticide pack": {"category": "hazardous waste"},
    "termite treatment chemical": {"category": "hazardous waste"},
    "fumigant canister": {"category": "hazardous waste"},
    "lab reagent bottle": {"category": "hazardous waste"},
    "expired tablet strips": {"category": "hazardous waste"},
    "expired capsules": {"category": "hazardous waste"},
    "expired syrup bottle": {"category": "hazardous waste"},
    "expired ointment tube": {"category": "hazardous waste"},
    "expired inhaler": {"category": "hazardous waste"},
    "expired eye drops": {"category": "hazardous waste"},
    "expired nasal spray": {"category": "hazardous waste"},
    "radioactive smoke detector": {"category": "hazardous waste"},
    "mosquito repellent refill": {"category": "hazardous waste"}, 
    "rat poison": {"category": "hazardous waste"}, 
    "phenyl bottle with liquid": {"category": "hazardous waste"}, 

    #infectious waste(yellow bin)
    "syringe": {"category": "infectious waste"},
    "needle": {"category": "infectious waste"},
    "blood soaked bandage": {"category": "infectious waste"},
    "lancet": {"category": "infectious waste"},
    "iv catheter": {"category": "infectious waste"},
    "blood bag": {"category": "infectious waste"},
    "urine bag": {"category": "infectious waste"},
    "drainage bag": {"category": "infectious waste"},
    "colostomy bag": {"category": "infectious waste"},
    "wound dressing": {"category": "infectious waste"},
    "surgical gloves": {"category": "infectious waste"},
    "examination gloves": {"category": "infectious waste"},
    "surgical mask": {"category": "infectious waste"},
    "n95 respirator": {"category": "infectious waste"},
    "face shield": {"category": "infectious waste"},
    "surgical gown": {"category": "infectious waste"},
    "isolation gown": {"category": "infectious waste"},
    "apron": {"category": "infectious waste"},
    "shoe cover": {"category": "infectious waste"},
    "surgical cap": {"category": "infectious waste"},
    "blood lancet": {"category": "infectious waste"},
    "glucose test strip": {"category": "infectious waste"},
    "suture needle": {"category": "infectious waste"},
    "suture thread": {"category": "infectious waste"},
    "scalpel blade": {"category": "infectious waste"},
    "biopsy needle": {"category": "infectious waste"},
    "bone marrow needle": {"category": "infectious waste"},
    "spinal needle": {"category": "infectious waste"},
    "epidural needle": {"category": "infectious waste"},
    "acupuncture needle": {"category": "infectious waste"},
    "insulin syringe": {"category": "infectious waste"},
    "pen needle": {"category": "infectious waste"},
    "infusion set": {"category": "infectious waste"},
    "transfusion set": {"category": "infectious waste"},
    "nasogastric tube": {"category": "infectious waste"},
    "urinary catheter": {"category": "infectious waste"},
    "chest drain tube": {"category": "infectious waste"},
    "tracheal tube": {"category": "infectious waste"},
    "endotracheal tube": {"category": "infectious waste"},
    "laryngeal mask": {"category": "infectious waste"},
    "oxygen mask": {"category": "infectious waste"},
    "nebulizer mask": {"category": "infectious waste"},
    "breathing circuit": {"category": "infectious waste"},
    "suction catheter": {"category": "infectious waste"},
    "suction canister": {"category": "infectious waste"},
    "wound swab": {"category": "infectious waste"},
    "throat swab": {"category": "infectious waste"},
    "nasal swab": {"category": "infectious waste"},
    "covid test kit": {"category": "infectious waste"},
    "rapid antigen test": {"category": "infectious waste"},
    "pregnancy test strip": {"category": "infectious waste"},
    "hiv test kit": {"category": "infectious waste"},
    "malaria test kit": {"category": "infectious waste"},
    "dengue test kit": {"category": "infectious waste"},
    "typhoid test kit": {"category": "infectious waste"},
    "hepatitis test kit": {"category": "infectious waste"},
    "blood culture bottle": {"category": "infectious waste"},
    "urine culture cup": {"category": "infectious waste"},
    "stool sample container": {"category": "infectious waste"},
    "sputum cup": {"category": "infectious waste"},
    "csf collection tube": {"category": "infectious waste"},
    "vacutainer tube": {"category": "infectious waste"},
    "blood collection tube": {"category": "infectious waste"},
    "specimen container": {"category": "infectious waste"},
    "pathology slide": {"category": "infectious waste"},
    "coverslip": {"category": "infectious waste"},
    "microbiology loop": {"category": "infectious waste"},
    "pipette tip": {"category": "infectious waste"},
    "culture dish": {"category": "infectious waste"},
    "agar plate": {"category": "infectious waste"},
    "pcr tube": {"category": "infectious waste"},
    "microcentrifuge tube": {"category": "infectious waste"},
    "cuvette": {"category": "infectious waste"},
    "dialysis membrane": {"category": "infectious waste"},
    "dialysis tubing": {"category": "infectious waste"},
    "peritoneal dialysis bag": {"category": "infectious waste"},
    "hemodialysis filter": {"category": "infectious waste"},
    "apheresis kit": {"category": "infectious waste"},
    "plasmapheresis set": {"category": "infectious waste"},
    "ostomy pouch": {"category": "infectious waste"},
    "ileostomy bag": {"category": "infectious waste"},
    "gastrostomy tube": {"category": "infectious waste"},
    "jejunostomy tube": {"category": "infectious waste"},
    "feeding tube": {"category": "infectious waste"},
    "rectal tube": {"category": "infectious waste"},
    "enema bag": {"category": "infectious waste"},
    "pessary": {"category": "infectious waste"},
    "iud removed": {"category": "infectious waste"},
    "contraceptive implant removed": {"category": "infectious waste"},
    "tampon": {"category": "infectious waste"},
    "sanitary pad": {"category": "infectious waste"},
    "soiled adult diaper": {"category": "infectious waste"},
    "incontinence pad": {"category": "infectious waste"},
    "pus soaked gauze": {"category": "infectious waste"},
    "absorbent pad": {"category": "infectious waste"},
    "hemostatic gauze": {"category": "infectious waste"},
    "surgical sponge": {"category": "infectious waste"},
    "laparotomy pad": {"category": "infectious waste"},
    "surgical drape": {"category": "infectious waste"},
    "wound vac foam": {"category": "infectious waste"},
    "negative pressure dressing": {"category": "infectious waste"},
    "tissue expander removed": {"category": "infectious waste"},
    "surgical drain": {"category": "infectious waste"},
    "jackson pratt drain": {"category": "infectious waste"},
    "hemovac drain": {"category": "infectious waste"},
    "penrose drain": {"category": "infectious waste"},
    "wound irrigation syringe": {"category": "infectious waste"},
    "debridement tool": {"category": "infectious waste"},
    "tongue depressor": {"category": "infectious waste"},
    "ear probe cover": {"category": "infectious waste"},
    "thermometer probe cover": {"category": "infectious waste"},
    "speculum cover": {"category": "infectious waste"},
    "proctoscope cover": {"category": "infectious waste"},
    "endoscope brush": {"category": "infectious waste"},
    "bronchoscope brush": {"category": "infectious waste"},
    "biopsy forceps": {"category": "infectious waste"},
    "cytology brush": {"category": "infectious waste"},
    "pap smear brush": {"category": "infectious waste"},
    "colposcopy swab": {"category": "infectious waste"},
    "amniocentesis needle": {"category": "infectious waste"},
    "placenta tissue": {"category": "infectious waste"},
    "umbilical cord": {"category": "infectious waste"},
    "surgical tissue removed": {"category": "infectious waste"},
    "human organ fragment": {"category": "infectious waste"},
    "autopsy waste": {"category": "infectious waste"},
    "mortuary waste": {"category": "infectious waste"},
    "embalming waste": {"category": "infectious waste"},
    "animal tissue lab": {"category": "infectious waste"},
    "contaminated lab coat": {"category": "infectious waste"},
    "contaminated ppe": {"category": "infectious waste"},
    "contaminated goggles": {"category": "infectious waste"},
    "biohazard bag": {"category": "infectious waste"},
    "sharps container": {"category": "infectious waste"},
    "kidney tray contaminated": {"category": "infectious waste"},
    "dressing trolley liner": {"category": "infectious waste"},
    "contaminated bed sheet": {"category": "infectious waste"},
    "contaminated pillow cover": {"category": "infectious waste"},
    "contaminated mattress cover": {"category": "infectious waste"},

    #biomedical waste(red bin)
    "syringe without needle": {"category": "biomedical waste"},
    "iv set tubing": {"category": "biomedical waste"},
    "iv bag plastic": {"category": "biomedical waste"},
    "saline bag": {"category": "biomedical waste"},
    "blood bag drained": {"category": "biomedical waste"},
    "urine bag": {"category": "biomedical waste"},
    "dialysis tubing": {"category": "biomedical waste"},
    "peritoneal dialysis bag": {"category": "biomedical waste"},
    "urinary catheter": {"category": "biomedical waste"},
    "iv catheter": {"category": "biomedical waste"},
    "suction catheter": {"category": "biomedical waste"},
    "nasogastric tube": {"category": "biomedical waste"},
    "chest drain tube": {"category": "biomedical waste"},
    "feeding tube": {"category": "biomedical waste"},
    "endotracheal tube": {"category": "biomedical waste"},
    "oxygen mask plastic": {"category": "biomedical waste"},
    "nebulizer mask": {"category": "biomedical waste"},
    "breathing circuit plastic": {"category": "biomedical waste"},
    "contaminated gloves": {"category": "biomedical waste"},
    "contaminated surgical mask": {"category": "biomedical waste"},
    "contaminated ppe kit": {"category": "biomedical waste"},
    "contaminated apron": {"category": "biomedical waste"},
    "shoe cover": {"category": "biomedical waste"},
    "surgical cap": {"category": "biomedical waste"},
    "face shield plastic": {"category": "biomedical waste"},
    "specimen container plastic": {"category": "biomedical waste"},
    "medicine vial plastic": {"category": "biomedical waste"},
    "vaccine vial plastic": {"category": "biomedical waste"},
    "blood collection tube plastic": {"category": "biomedical waste"},
    "sample transport bag": {"category": "biomedical waste"},
    "colostomy bag": {"category": "biomedical waste"},
    "ileostomy bag": {"category": "biomedical waste"},
    "ostomy pouch": {"category": "biomedical waste"},
    "drainage bag": {"category": "biomedical waste"},
    "suction canister plastic": {"category": "biomedical waste"},
    "biohazard swab plastic handle": {"category": "biomedical waste"},

    #e-waste(black bin)
    "e waste": {"category": "e waste"},
    "rechargeable nicd battery pack": {"category": "e waste"},
    "rechargeable lithium battery pack": {"category": "e waste"},
    "mobile phone battery": {"category": "e waste"},
    "laptop battery": {"category": "e waste"},
    "tablet battery": {"category": "e waste"},
    "power bank battery": {"category": "e waste"},
    "drill battery pack": {"category": "e waste"},
    "camera battery pack": {"category": "e waste"},
    "ups battery": {"category": "e waste"},
    "inverter battery": {"category": "e waste"},
    "sealed lead battery": {"category": "e waste"},
    "hearing aid battery": {"category": "e waste"},
    "watch battery": {"category": "e waste"},
    "coin cell battery": {"category": "e waste"},
    "broken smartphone": {"category": "e waste"},
    "broken feature phone": {"category": "e waste"},
    "broken tablet": {"category": "e waste"},
    "broken laptop": {"category": "e waste"},
    "broken desktop cpu": {"category": "e waste"},
    "broken monitor": {"category": "e waste"},
    "crt monitor": {"category": "e waste"},
    "lcd panel waste": {"category": "e waste"},
    "led tv board": {"category": "e waste"},
    "computer motherboard": {"category": "e waste"},
    "graphics card waste": {"category": "e waste"},
    "sound card waste": {"category": "e waste"},
    "ram module waste": {"category": "e waste"},
    "hard disk drive": {"category": "e waste"},
    "solid state drive": {"category": "e waste"},
    "optical drive": {"category": "e waste"},
    "smps unit": {"category": "e waste"},
    "power adapter": {"category": "e waste"},
    "charger head": {"category": "e waste"},
    "usb cable damaged": {"category": "e waste"},
    "network router": {"category": "e waste"},
    "wifi modem": {"category": "e waste"},
    "set top box": {"category": "e waste"},
    "printer cartridge": {"category": "e waste"},
    "toner cartridge": {"category": "e waste"},
    "ink cartridge": {"category": "e waste"},
    "waste toner powder": {"category": "e waste"},
    "keyboard waste": {"category": "e waste"},
    "mouse waste": {"category": "e waste"},
    "webcam waste": {"category": "e waste"},
    "earphone waste": {"category": "e waste"},
    "headphone waste": {"category": "e waste"},
    "circuit board scrap": {"category": "e waste"},
    "electronic relay": {"category": "e waste"},
    "fuse waste": {"category": "e waste"},
    "switch board waste": {"category": "e waste"},
    "extension board waste": {"category": "e waste"},
    "electrical wire insulation": {"category": "e waste"},
    "solder dross": {"category": "e waste"},
    "lead solder wire": {"category": "e waste"},
    "graphics card": {"category": "e waste"},
    "sound card": {"category": "e waste"},
    "damaged smartphone screen": {"category": "e waste"},
    "cracked smartphone display": {"category": "e waste"},
    "smartphone motherboard scrap": {"category": "e waste"},
    "smartphone camera module": {"category": "e waste"},
    "smartphone charging port": {"category": "e waste"},
    "smartphone speaker module": {"category": "e waste"},
    "smartphone vibration motor": {"category": "e waste"},
    "smartphone fingerprint sensor": {"category": "e waste"},
    "smartphone back cover": {"category": "e waste"},
    "smartphone sim tray": {"category": "e waste"},
    "smartphone flex cable": {"category": "e waste"},
    "smartphone battery connector": {"category": "e waste"},
    "smartphone antenna module": {"category": "e waste"},
    "smartphone volume button strip": {"category": "e waste"},
    "smartphone power button strip": {"category": "e waste"},
    "smartphone earpiece speaker": {"category": "e waste"},
    "smartphone microphone board": {"category": "e waste"},
    "smartphone front camera module": {"category": "e waste"},
    "smartphone rear camera module": {"category": "e waste"},
    "smartphone display frame": {"category": "e waste"},
    "feature phone keypad board": {"category": "e waste"},
    "feature phone screen": {"category": "e waste"},
    "feature phone battery terminal": {"category": "e waste"},
    "feature phone speaker": {"category": "e waste"},
    "feature phone microphone": {"category": "e waste"},
    "feature phone charger pin": {"category": "e waste"},
    "tablet touch panel": {"category": "e waste"},
    "tablet lcd panel": {"category": "e waste"},
    "tablet motherboard": {"category": "e waste"},
    "tablet charging board": {"category": "e waste"},
    "tablet camera module": {"category": "e waste"},
    "tablet speaker module": {"category": "e waste"},
    "tablet power ic board": {"category": "e waste"},
    "tablet wifi module": {"category": "e waste"},
    "tablet back housing": {"category": "e waste"},
    "tablet button flex": {"category": "e waste"},
    "smartwatch circuit board": {"category": "e waste"},
    "smartwatch battery": {"category": "e waste"},
    "smartwatch display": {"category": "e waste"},
    "smartwatch charging dock": {"category": "e waste"},
    "fitness band circuit": {"category": "e waste"},
    "fitness band display": {"category": "e waste"},
    "fitness band charger": {"category": "e waste"},
    "wireless earbuds case board": {"category": "e waste"},
    "wireless earbud battery": {"category": "e waste"},
    "wireless earbud driver": {"category": "e waste"},
    "bluetooth headset pcb": {"category": "e waste"},
    "bluetooth headset battery": {"category": "e waste"},
    "bluetooth neckband pcb": {"category": "e waste"},
    "bluetooth neckband battery": {"category": "e waste"},
    "laptop motherboard": {"category": "e waste"},
    "laptop display panel": {"category": "e waste"},
    "laptop keyboard": {"category": "e waste"},
    "laptop touchpad module": {"category": "e waste"},
    "laptop hinge set": {"category": "e waste"},
    "laptop cooling fan": {"category": "e waste"},
    "laptop heat sink": {"category": "e waste"},
    "laptop ram stick": {"category": "e waste"},
    "laptop wifi card": {"category": "e waste"},
    "laptop bluetooth card": {"category": "e waste"},
    "laptop dc jack board": {"category": "e waste"},
    "laptop speaker set": {"category": "e waste"},
    "laptop webcam module": {"category": "e waste"},
    "laptop battery pack": {"category": "e waste"},
    "laptop charger adapter": {"category": "e waste"},
    "laptop power cable": {"category": "e waste"},
    "laptop hard drive": {"category": "e waste"},
    "laptop ssd": {"category": "e waste"},
    "laptop dvd drive": {"category": "e waste"},
    "laptop cmos battery": {"category": "e waste"},
    "desktop motherboard": {"category": "e waste"},
    "desktop cpu processor": {"category": "e waste"},
    "desktop ram module": {"category": "e waste"},
    "desktop power supply unit": {"category": "e waste"},
    "desktop cooling fan": {"category": "e waste"},
    "desktop heat sink": {"category": "e waste"},
    "desktop cabinet panel": {"category": "e waste"},
    "desktop front panel board": {"category": "e waste"},
    "desktop sata cable": {"category": "e waste"},
    "desktop pci card": {"category": "e waste"},
    "desktop lan card": {"category": "e waste"},
    "desktop wifi adapter card": {"category": "e waste"},
    "desktop usb expansion card": {"category": "e waste"},
    "desktop sound card module": {"category": "e waste"},
    "desktop graphics card module": {"category": "e waste"},
    "desktop smps fan": {"category": "e waste"},
    "desktop cmos battery": {"category": "e waste"},
    "server motherboard": {"category": "e waste"},
    "server ram module": {"category": "e waste"},
    "server power supply": {"category": "e waste"},
    "server raid card": {"category": "e waste"},
    "server network card": {"category": "e waste"},
    "all in one pc board": {"category": "e waste"},
    "all in one pc screen": {"category": "e waste"},
    "mini pc motherboard": {"category": "e waste"},
    "mini pc power adapter": {"category": "e waste"},
    "chromebook motherboard": {"category": "e waste"},
    "chromebook battery": {"category": "e waste"},
    "chromebook screen": {"category": "e waste"},
    "chromebook keyboard": {"category": "e waste"},
    "external gpu enclosure board": {"category": "e waste"},
    "motherboard io shield": {"category": "e waste"},
    "cpu cooler pump": {"category": "e waste"},
    "liquid cooler controller": {"category": "e waste"},
    "thermal paste tube electronic": {"category": "e waste"},
    "bios chip": {"category": "e waste"},
    "northbridge chip": {"category": "e waste"},
    "southbridge chip": {"category": "e waste"},
    "vrm heat sink": {"category": "e waste"},
    "m.2 ssd module": {"category": "e waste"},
    "usb keyboard": {"category": "e waste"},
    "mechanical keyboard pcb": {"category": "e waste"},
    "keyboard membrane sheet": {"category": "e waste"},
    "keyboard key switch": {"category": "e waste"},
    "usb mouse": {"category": "e waste"},
    "wireless mouse pcb": {"category": "e waste"},
    "mouse scroll wheel sensor": {"category": "e waste"},
    "mouse receiver dongle": {"category": "e waste"},
    "gaming mouse pcb": {"category": "e waste"},
    "trackball mouse pcb": {"category": "e waste"},
    "usb webcam": {"category": "e waste"},
    "hd webcam board": {"category": "e waste"},
    "webcam microphone board": {"category": "e waste"},
    "usb microphone board": {"category": "e waste"},
    "studio microphone pcb": {"category": "e waste"},
    "headphone driver unit": {"category": "e waste"},
    "headphone headband wiring": {"category": "e waste"},
    "earphone driver unit": {"category": "e waste"},
    "earphone inline remote pcb": {"category": "e waste"},
    "speaker crossover board": {"category": "e waste"},
    "bluetooth speaker pcb": {"category": "e waste"},
    "portable speaker battery": {"category": "e waste"},
    "soundbar control board": {"category": "e waste"},
    "subwoofer amplifier board": {"category": "e waste"},
    "printer main board": {"category": "e waste"},
    "printer scanner unit": {"category": "e waste"},
    "printer carriage motor": {"category": "e waste"},
    "printer fuser unit": {"category": "e waste"},
    "printer power board": {"category": "e waste"},
    "inkjet printhead board": {"category": "e waste"},
    "laser printer drum unit": {"category": "e waste"},
    "barcode scanner board": {"category": "e waste"},
    "receipt printer board": {"category": "e waste"},
    "flatbed scanner board": {"category": "e waste"},
    "document scanner board": {"category": "e waste"},
    "projector lamp module": {"category": "e waste"},
    "projector mainboard": {"category": "e waste"},
    "projector color wheel": {"category": "e waste"},
    "projector power board": {"category": "e waste"},
    "game controller pcb": {"category": "e waste"},
    "joystick controller board": {"category": "e waste"},
    "console controller battery": {"category": "e waste"},
    "gaming console motherboard": {"category": "e waste"},
    "gaming console fan": {"category": "e waste"},
    "gaming console power board": {"category": "e waste"},
    "vr headset mainboard": {"category": "e waste"},
    "vr controller board": {"category": "e waste"},
    "drawing tablet board": {"category": "e waste"},
    "pen tablet stylus board": {"category": "e waste"},
    "digital pen battery": {"category": "e waste"},
    "wifi router board": {"category": "e waste"},
    "wifi router antenna": {"category": "e waste"},
    "wifi extender board": {"category": "e waste"},
    "broadband modem board": {"category": "e waste"},
    "fiber ont board": {"category": "e waste"},
    "adsl modem board": {"category": "e waste"},
    "network switch board": {"category": "e waste"},
    "managed switch power unit": {"category": "e waste"},
    "ethernet hub board": {"category": "e waste"},
    "access point board": {"category": "e waste"},
    "cctv dvr board": {"category": "e waste"},
    "cctv nvr board": {"category": "e waste"},
    "ip camera board": {"category": "e waste"},
    "ip camera poe module": {"category": "e waste"},
    "set top box motherboard": {"category": "e waste"},
    "satellite receiver board": {"category": "e waste"},
    "tv tuner card": {"category": "e waste"},
    "rf amplifier module": {"category": "e waste"},
    "signal booster board": {"category": "e waste"},
    "telecom gateway board": {"category": "e waste"},
    "voip phone board": {"category": "e waste"},
    "cordless phone base board": {"category": "e waste"},
    "cordless handset board": {"category": "e waste"},
    "landline phone pcb": {"category": "e waste"},
    "intercom panel board": {"category": "e waste"},
    "biometric attendance board": {"category": "e waste"},
    "rfid reader board": {"category": "e waste"},
    "nfc reader module": {"category": "e waste"},
    "gsm module board": {"category": "e waste"},
    "gps tracker board": {"category": "e waste"},
    "led tv motherboard": {"category": "e waste"},
    "led tv power board": {"category": "e waste"},
    "led tv tcon board": {"category": "e waste"},
    "led tv backlight strip": {"category": "e waste"},
    "led tv speaker module": {"category": "e waste"},
    "smart tv wifi module": {"category": "e waste"},
    "oled tv control board": {"category": "e waste"},
    "monitor power board": {"category": "e waste"},
    "monitor tcon board": {"category": "e waste"},
    "monitor stand electronics": {"category": "e waste"},
    "lcd inverter board": {"category": "e waste"},
    "plasma tv board": {"category": "e waste"},
    "dvd player motherboard": {"category": "e waste"},
    "blu ray player board": {"category": "e waste"},
    "media player box board": {"category": "e waste"},
    "digital photo frame board": {"category": "e waste"},
    "home theater amplifier board": {"category": "e waste"},
    "av receiver board": {"category": "e waste"},
    "car stereo head unit board": {"category": "e waste"},
    "car stereo amplifier board": {"category": "e waste"},
    "dashcam board": {"category": "e waste"},
    "action camera board": {"category": "e waste"},
    "drone flight controller": {"category": "e waste"},
    "drone camera gimbal board": {"category": "e waste"},
    "drone remote controller board": {"category": "e waste"},
    "drone battery pack": {"category": "e waste"},
    "camcorder main board": {"category": "e waste"},
    "dslr camera shutter board": {"category": "e waste"},
    "dslr camera sensor board": {"category": "e waste"},
    "mirrorless camera board": {"category": "e waste"},
    "microwave control board": {"category": "e waste"},
    "microwave inverter board": {"category": "e waste"},
    "induction cooktop board": {"category": "e waste"},
    "electric kettle thermostat board": {"category": "e waste"},
    "rice cooker pcb": {"category": "e waste"},
    "air fryer control board": {"category": "e waste"},
    "refrigerator control board": {"category": "e waste"},
    "refrigerator inverter board": {"category": "e waste"},
    "washing machine control board": {"category": "e waste"},
    "washing machine motor driver board": {"category": "e waste"},
    "dishwasher control board": {"category": "e waste"},
    "water purifier uv board": {"category": "e waste"},
    "water purifier smps board": {"category": "e waste"},
    "air conditioner pcb": {"category": "e waste"},
    "air conditioner remote pcb": {"category": "e waste"},
    "ceiling fan remote receiver board": {"category": "e waste"},
    "inverter stabilizer board": {"category": "e waste"},
    "ups control board": {"category": "e waste"},
    "inverter control card": {"category": "e waste"},
    "battery charger circuit board": {"category": "e waste"},
    "solar charge controller board": {"category": "e waste"},
    "solar inverter board": {"category": "e waste"},
    "led driver module": {"category": "e waste"},
    "emergency light pcb": {"category": "e waste"},
    "rechargeable torch pcb": {"category": "e waste"},
    "electric trimmer pcb": {"category": "e waste"},
    "hair dryer control board": {"category": "e waste"},
    "electric shaver pcb": {"category": "e waste"},
    "toothbrush charger board": {"category": "e waste"},
    "weighing scale pcb": {"category": "e waste"},
    "arduino board broken": {"category": "e waste"}, 
    "raspberry pi broken": {"category": "e waste"}, 
    "breadboard damaged": {"category": "e waste"}, 
    "jumper wires scrap": {"category": "e waste"}, 
    "led components scrap": {"category": "e waste"}, 
    "smart bulb broken": {"category": "e waste"}, 
}

bin_by_waste_type = {
    "biomedical waste": "Red",
    "e waste": "Black",
    "hazardous waste": "Black",
    "dry waste": "Blue",
    "wet waste": "Green",
    "e-waste": "Black",
    "infectious waste": "Yellow"
}

#tips
category_tips = {
    "wet waste": "Ensure no plastic bags or wrappers are mixed. Best for composting.",
    "dry waste": "Empty and rinse out any food/liquid residue before disposing. Crush boxes to save space.",
    "hazardous waste": "Handle with care. Keep tightly sealed in its original container if possible.",
    "biomedical waste": "Wrap securely in newspaper or a dedicated bag. Do NOT mix with dry/wet waste to prevent infections.",
    "e waste": "Do not dismantle. Tape over battery terminals if exposed to prevent fire risks.",
    "e-waste": "Do not dismantle. Tape over battery terminals if exposed to prevent fire risks.",
    "infectious waste": "Never compress by hand and hand over only to an authorised biomedical waste collector. Do not mix with general waste."
}

special_tips = {
    "pizza box clean": "If the bottom is very greasy, tear it off and put the greasy part in Wet Waste (Green Bin).",
    "broken smartphone": "Ensure you wipe your personal data and remove SIM/Memory cards before giving it to an e-waste drive.",
    "laptop hard drive": "Physically destroy the drive or wipe it using software before disposal to protect privacy.",
    "eggshells": "Crush them into smaller pieces before putting them in the green bin to speed up composting.",
    "plastic bottle": "Crush the bottle and put the cap back on before throwing it in the blue bin.",
    "glass jar": "Rinse thoroughly. If broken, wrap it in thick paper and label it 'Broken Glass' to protect sanitation workers.",
    "battery": "Never throw batteries in regular trash; they can leak toxic chemicals or cause fires.",
    "used syringe": "Put it in a puncture-proof container (like a thick plastic bottle) before throwing it in the red bin.",
    "used tea leaves": "Squeeze out excess water before disposing. Excellent for plant fertilizer!"
}

# Auto augment the database on load
for waste_item, data in waste_database.items():
    category = data.get("category", "").strip().lower()
    # bin assignment
    if category in bin_by_waste_type:
        data["bin"] = bin_by_waste_type[category]   
    # tips assignment
    if waste_item in special_tips:
        data["tip"] = special_tips[waste_item] 
    elif category in category_tips:
        data["tip"] = category_tips[category]  
    else:
        data["tip"] = "Dispose of responsibly according to local guidelines."

def get_waste_info(item_name: str):
    name_clean = item_name.strip().lower()
    if name_clean in waste_database:
        return waste_database[name_clean]
    return None
